import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


import ReactQueryProvider from "@/providers/ReactQueryProvider";
import Navbar from "@/layout/Navbar";
import Footer from "@/layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Crypto Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <Navbar />
          {children}
          <Footer />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
